import java.time.Duration

plugins {
    kotlin("jvm") version "2.3.10"
    application
    id("org.jlleitschuh.gradle.ktlint") version "14.0.1"
    id("com.google.protobuf") version "0.9.6"
}

group = "com.example"
version = "0.1.0"

repositories {
    mavenCentral()
}

val ktorVersion = "3.4.0"
val hopliteVersion = "2.9.0"
val micrometerVersion = "1.16.3"
val grpcVersion = "1.79.0"
val grpcKotlinVersion = "1.5.0"
val protobufVersion = "3.25.5"
val exposedVersion = "0.58.0"

dependencies {
    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    implementation("io.ktor:ktor-server-core-jvm:$ktorVersion")
    implementation("io.ktor:ktor-server-netty-jvm:$ktorVersion")
    implementation("io.ktor:ktor-server-websockets-jvm:$ktorVersion")

    implementation("ch.qos.logback:logback-classic:1.5.18")
    implementation("io.github.oshai:kotlin-logging-jvm:7.0.3")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.21.0")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.21.0")
    implementation("com.sksamuel.hoplite:hoplite-core:$hopliteVersion")
    implementation("com.sksamuel.hoplite:hoplite-yaml:$hopliteVersion")
    implementation("org.mindrot:jbcrypt:0.4")
    implementation("io.micrometer:micrometer-core:$micrometerVersion")
    implementation("io.micrometer:micrometer-registry-prometheus:$micrometerVersion")

    implementation("io.lettuce:lettuce-core:7.4.0.RELEASE")

    // Exposed (Kotlin SQL framework)
    implementation("org.jetbrains.exposed:exposed-core:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")
    // Connection pool
    implementation("com.zaxxer:HikariCP:6.2.1")
    // JDBC driver
    implementation("org.postgresql:postgresql:42.7.5")
    // Schema migration
    implementation("org.flywaydb:flyway-core:11.3.0")
    implementation("org.flywaydb:flyway-database-postgresql:11.3.0")

    // gRPC / Protobuf
    implementation("io.grpc:grpc-netty-shaded:$grpcVersion")
    implementation("io.grpc:grpc-protobuf:$grpcVersion")
    implementation("io.grpc:grpc-stub:$grpcVersion")
    implementation("io.grpc:grpc-kotlin-stub:$grpcKotlinVersion")

    // Test: H2 in Postgres mode
    testImplementation("com.h2database:h2:2.3.232")

    testImplementation("io.grpc:grpc-testing:$grpcVersion")
    testImplementation("io.grpc:grpc-inprocess:$grpcVersion")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
    testImplementation("org.junit.jupiter:junit-jupiter:6.0.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("io.ktor:ktor-server-test-host-jvm:$ktorVersion")
    testImplementation("io.ktor:ktor-client-cio-jvm:$ktorVersion")
    testImplementation("io.ktor:ktor-client-websockets-jvm:$ktorVersion")
}

kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("dev.ambon.MainKt")
}

tasks.test {
    useJUnitPlatform()
    // Prevent the entire test suite from hanging indefinitely (e.g. due to coroutine
    // leaks or gRPC streams that never close). Individual test timeouts are configured
    // in junit-platform.properties; this is a backstop for the Gradle process itself.
    timeout = Duration.ofMinutes(5)
}

// Map -Pconfig.X=Y project properties to config.override.X system properties.
// Provides a shell-safe, uniform way to override any Hoplite config value at runtime.
// Example: ./gradlew run -Pconfig.ambonMUD.logging.level=DEBUG
//          ./gradlew run -Pconfig.ambonMUD.server.tickMillis=500
fun JavaExec.applyConfigOverrides() {
    project.properties
        .filter { (k, _) -> k.startsWith("config.") }
        .forEach { (k, v) -> systemProperty("config.override.$k", v.toString()) }
}

tasks.named<JavaExec>("run") {
    applyConfigOverrides()
}

tasks.register<JavaExec>("demo") {
    group = "application"
    description = "Runs AmbonMUD and opens the browser demo client."
    mainClass.set(application.mainClass)
    classpath = project.extensions.getByType(org.gradle.api.tasks.SourceSetContainer::class.java)["main"].runtimeClasspath
    standardInput = System.`in`
    systemProperty("config.override.ambonMUD.demo.autoLaunchBrowser", "true")
    applyConfigOverrides()
}

// Suppress ktlint violations in protobuf/grpc generated sources.
// The filter lambda works for ktlintCheck but not ktlintFormat (plugin quirk).
// Writing a child .editorconfig into build/generated/ is the reliable cross-task fix.
val suppressKtlintForGenerated by tasks.registering {
    val editorConfigFile = layout.buildDirectory.file("generated/.editorconfig")
    outputs.file(editorConfigFile)
    doLast {
        editorConfigFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText(
                """
                [*.kt]
                ktlint_standard_function-naming = disabled
                ktlint_standard_filename = disabled
                ktlint_standard_max-line-length = disabled
                """.trimIndent(),
            )
        }
    }
}

ktlint {
    verbose.set(true)
    android.set(false)
    filter {
        exclude { entry ->
            val normalized = entry.file.path.replace("\\", "/")
            normalized.contains("build/generated")
        }
    }
}

// Ensure the editorconfig shim exists before any ktlint task inspects generated sources.
tasks.matching { it.name.startsWith("runKtlint") }.configureEach {
    dependsOn(suppressKtlintForGenerated)
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobufVersion"
    }
    plugins {
        create("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
        }
        create("grpckt") {
            artifact = "io.grpc:protoc-gen-grpc-kotlin:$grpcKotlinVersion:jdk8@jar"
        }
    }
    generateProtoTasks {
        all().forEach { task ->
            task.plugins {
                create("grpc")
                create("grpckt")
            }
        }
    }
}
